// ── exportText.js ─────────────────────────────────────────────────────────────
// Generates a plain-text CGPA summary for pasting into emails, WhatsApp,
// admission forms, or scholarship applications.
//
// Deliberately human-readable. No markdown, no symbols that break on SMS.


/**
 * Builds the full plain-text summary string.
 *
 * @param {Object} params
 * @param {Object|null}  params.institution
 * @param {Object}       params.student
 * @param {Array}        params.semesters
 * @param {number|null}  params.cgpa
 * @param {string|null}  params.degreeClass
 * @param {Array}        params.semesterSummaries  - [{ label, gpa, totalCU, totalQP }]
 * @param {number}       params.totalCU
 * @param {number}       params.totalQP
 * @param {boolean}      params.useUILegacyScale
 *
 * @returns {string}
 */
export function buildTextSummary({
  institution,
  student,
  semesters,
  cgpa,
  degreeClass,
  semesterSummaries,
  totalCU,
  totalQP,
  useUILegacyScale = false,
}) {
  const lines = [];
  const now   = new Date();

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push("NG CGPA - Academic Performance Summary");
  lines.push("Generated by NG CGPA (ngcgpa.ng) | Built by Nonso [ELUSK]");
  lines.push(formatDate(now));
  lines.push(divider(44));

  // ── Institution ─────────────────────────────────────────────────────────────
  if (institution) {
    lines.push(`University:   ${institution.name}`);
    lines.push(
      `Scale:        ${institution.scale}.0` +
      (useUILegacyScale ? " (Legacy 7.0 — Pre-2016/2017)" : "")
    );
  } else {
    lines.push("University:   Not selected");
  }

  // ── Student ─────────────────────────────────────────────────────────────────
  if (hasStudentData(student)) {
    lines.push(divider(44));

    if (student.name)            lines.push(`Name:         ${student.name}`);
    if (student.department)      lines.push(`Department:   ${student.department}`);
    if (student.faculty)         lines.push(`Faculty:      ${student.faculty}`);
    if (student.matricNumber)    lines.push(`Matric No.:   ${student.matricNumber}`);
    if (student.level)           lines.push(`Level:        ${student.level}`);
    if (student.academicSession) lines.push(`Session:      ${student.academicSession}`);
  }

  // ── CGPA Summary ────────────────────────────────────────────────────────────
  lines.push(divider(44));
  lines.push("RESULT SUMMARY");
  lines.push(divider(44));

  if (cgpa !== null && cgpa !== undefined) {
    lines.push(`CGPA:         ${cgpa.toFixed(2)} / ${institution?.scale?.toFixed(1) || "5.0"}`);
    lines.push(`Class:        ${degreeClass || "Not determined"}`);
  } else {
    lines.push("CGPA:         No data entered yet.");
  }

  lines.push(`Total Credit Units:    ${totalCU}`);
  lines.push(`Total Quality Points:  ${round2(totalQP)}`);
  lines.push(`Semesters Completed:   ${countCompletedSemesters(semesters)}`);

  // ── Semester Breakdown ───────────────────────────────────────────────────────
  if (Array.isArray(semesterSummaries) && semesterSummaries.length > 0) {
    lines.push(divider(44));
    lines.push("SEMESTER BREAKDOWN");
    lines.push(divider(44));

    const col1 = longestLabel(semesterSummaries) + 2;

    // Header row
    lines.push(
      padRight("Semester", col1) +
      padLeft("CU", 5)  + "  " +
      padLeft("QP", 7)  + "  " +
      padLeft("GPA", 6)
    );
    lines.push(divider(col1 + 5 + 2 + 7 + 2 + 6));

    for (const sem of semesterSummaries) {
      if (sem.gpa === null && sem.totalCU === 0) continue;
      lines.push(
        padRight(sem.label || "Semester", col1) +
        padLeft(String(sem.totalCU), 5)              + "  " +
        padLeft(round2(sem.totalQP).toFixed(2), 7)   + "  " +
        padLeft(sem.gpa !== null ? sem.gpa.toFixed(2) : "—", 6)
      );
    }
  }

  // ── Course Details ───────────────────────────────────────────────────────────
  if (Array.isArray(semesters) && semesters.length > 0) {
    for (const sem of semesters) {
      if (!Array.isArray(sem.courses) || sem.courses.length === 0) continue;

      lines.push(divider(44));
      lines.push((sem.label || "Semester").toUpperCase());
      lines.push(divider(44));

      // Column header
      lines.push(
        padRight("Course", 12) +
        padLeft("CU", 4) + "  " +
        padLeft("Score", 7) + "  " +
        padLeft("Grade", 6) + "  " +
        padLeft("GP", 4) + "  " +
        padLeft("QP", 6)
      );
      lines.push(divider(12 + 4 + 2 + 7 + 2 + 6 + 2 + 4 + 2 + 6));

      for (const course of sem.courses) {
        const score    = course.score !== null && course.score !== undefined
          ? String(course.score)
          : "—";
        const grade    = course.grade    || "—";
        const gp       = course.gradePoint !== null ? String(course.gradePoint) : "—";
        const qp       = course.qualityPoint !== null
          ? round2(course.qualityPoint).toFixed(2)
          : "—";
        const cu       = String(course.creditUnits || "—");
        const name     = truncate(course.name || "Unnamed", 12);

        lines.push(
          padRight(name, 12)   +
          padLeft(cu, 4)    + "  " +
          padLeft(score, 7) + "  " +
          padLeft(grade, 6) + "  " +
          padLeft(gp, 4)    + "  " +
          padLeft(qp, 6)
        );
      }
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push(divider(44));
  lines.push("This summary was generated by NG CGPA.");
  lines.push("ngcgpa.ng | Built by Nonso [ELUSK]");
  lines.push(
    "Note: Always verify your CGPA with your institution's official records."
  );

  return lines.join("\n");
}


/**
 * Triggers a browser download of the text summary as a .txt file.
 *
 * @param {string} text
 * @param {string} institutionId
 * @param {string} studentName
 */
export function downloadTextSummary(text, institutionId, studentName) {
  const filename = buildTextFilename(institutionId, studentName);
  const blob     = new Blob([text], { type: "text/plain;charset=utf-8" });
  triggerDownload(blob, filename);
}


/**
 * Copies the text summary to the clipboard.
 * Returns a promise that resolves to true on success, false on failure.
 *
 * @param {string} text
 * @returns {Promise<boolean>}
 */
export async function copyTextToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers / restricted contexts
    try {
      const el = document.createElement("textarea");
      el.value = text;
      el.style.position = "fixed";
      el.style.opacity  = "0";
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      return true;
    } catch {
      return false;
    }
  }
}


// ── Filename Builder ──────────────────────────────────────────────────────────

function buildTextFilename(institutionId, studentName) {
  const id   = (institutionId  || "EXPORT").toUpperCase().replace(/[^A-Z0-9]/g, "");
  const name = studentName
    ? studentName.trim().replace(/\s+/g, "_").replace(/[^A-Za-z0-9_]/g, "").slice(0, 20)
    : "Student";
  const ts   = buildTimestamp();
  return `NGCGPA_${name}_${id}_${ts}.txt`;
}

function buildTimestamp() {
  const now = new Date();
  const Y   = now.getFullYear();
  const M   = String(now.getMonth() + 1).padStart(2, "0");
  const D   = String(now.getDate()).padStart(2, "0");
  const h   = String(now.getHours()).padStart(2, "0");
  const m   = String(now.getMinutes()).padStart(2, "0");
  const s   = String(now.getSeconds()).padStart(2, "0");
  return `${Y}${M}${D}_${h}${m}${s}`;
}


// ── Formatting Helpers ────────────────────────────────────────────────────────

function formatDate(date) {
  try {
    return date.toLocaleDateString("en-NG", {
      weekday: "long",
      day:     "numeric",
      month:   "long",
      year:    "numeric",
    }) + " at " + date.toLocaleTimeString("en-NG", {
      hour:   "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  } catch {
    return date.toISOString();
  }
}

function divider(length) {
  return "─".repeat(Math.max(4, length));
}

function padRight(str, len) {
  return String(str).padEnd(len, " ");
}

function padLeft(str, len) {
  return String(str).padStart(len, " ");
}

function truncate(str, max) {
  if (str.length <= max) return str;
  return str.slice(0, max - 1) + ".";
}

function longestLabel(summaries) {
  return summaries.reduce(
    (max, s) => Math.max(max, (s.label || "").length),
    8
  );
}

function round2(n) {
  if (n === null || n === undefined || isNaN(n)) return 0;
  return Math.round(n * 100) / 100;
}

function countCompletedSemesters(semesters) {
  if (!Array.isArray(semesters)) return 0;
  return semesters.filter(
    (s) => Array.isArray(s.courses) && s.courses.length > 0
  ).length;
}

function hasStudentData(student) {
  if (!student) return false;
  return Object.values(student).some((v) => v && String(v).trim() !== "");
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a   = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}