// ── pdfTemplate.js ────────────────────────────────────────────────────────────
// PDF visual constants, shared drawing helpers, and autoTable style definitions.
// exportPDF.js calls these helpers. No jsPDF import needed in components.


// ── Page Dimensions (A4 in mm) ────────────────────────────────────────────────
export const PAGE_WIDTH   = 210;
export const PAGE_HEIGHT  = 297;

export const MARGIN = {
  top:    20,
  bottom: 20,
  left:   18,
  right:  18,
};

export const CONTENT_WIDTH = PAGE_WIDTH - MARGIN.left - MARGIN.right;


// ── Colors (RGB arrays) ───────────────────────────────────────────────────────
export const PDF_COLOR = {
  primary:        [27,  67,  50],
  primaryLight:   [45,  106, 79],
  accent:         [244, 162, 97],
  accentLight:    [253, 220, 181],
  textPrimary:    [26,  26,  26],
  textSecondary:  [92,  92,  92],
  textMuted:      [154, 154, 154],
  border:         [214, 208, 200],
  surface:        [250, 250, 248],
  surface2:       [240, 237, 232],
  danger:         [193, 18,  31],
  success:        [56,  102, 65],
  warning:        [188, 108, 37],
  white:          [255, 255, 255],
  black:          [0,   0,   0],
  classFirst:     [56,  102, 65],
  classUpper:     [27,  67,  50],
  classLower:     [188, 108, 37],
  classThird:     [123, 79,  18],
  classPass:      [92,  92,  92],
  classFail:      [193, 18,  31],
};


// ── Degree Class Color ────────────────────────────────────────────────────────
export function classColor(shortClass) {
  if (!shortClass) return PDF_COLOR.textSecondary;
  const s = shortClass.toLowerCase();
  if (s.includes("first"))   return PDF_COLOR.classFirst;
  if (s.includes("2:1") || s.includes("upper")) return PDF_COLOR.classUpper;
  if (s.includes("2:2") || s.includes("lower")) return PDF_COLOR.classLower;
  if (s.includes("third"))   return PDF_COLOR.classThird;
  if (s.includes("pass"))    return PDF_COLOR.classPass;
  return PDF_COLOR.classFail;
}


// ── Typography ────────────────────────────────────────────────────────────────
export const PDF_FONT = {
  regular:  { family: "helvetica", style: "normal"  },
  bold:     { family: "helvetica", style: "bold"    },
  italic:   { family: "helvetica", style: "italic"  },
};

export const PDF_SIZE = {
  display:   28,
  h1:        16,
  h2:        13,
  h3:        11,
  body:       9,
  small:      8,
  micro:      7,
  watermark: 30,
};


// ── Watermark ─────────────────────────────────────────────────────────────────

/**
 * Adds a faint diagonal watermark on the current page.
 * Uses GState for opacity. Falls back to near-white gray if GState is unsupported.
 */
export function addWatermark(doc) {
  const cx = PAGE_WIDTH  / 2;
  const cy = PAGE_HEIGHT / 2;

  try {
    doc.saveGraphicsState();
    const gs = doc.GState({ opacity: 0.07 });
    doc.setGState(gs);
    doc.setFont(PDF_FONT.bold.family, PDF_FONT.bold.style);
    doc.setFontSize(PDF_SIZE.watermark);
    doc.setTextColor(...PDF_COLOR.black);
    doc.text("NG CGPA  \u00B7  Nonso [ELUSK]", cx, cy, {
      align:    "center",
      angle:    45,
      baseline: "middle",
    });
    doc.restoreGraphicsState();
  } catch {
    doc.setFont(PDF_FONT.bold.family, PDF_FONT.bold.style);
    doc.setFontSize(PDF_SIZE.watermark);
    doc.setTextColor(248, 248, 248);
    doc.text("NG CGPA  \u00B7  Nonso [ELUSK]", cx, cy, {
      align:    "center",
      angle:    45,
      baseline: "middle",
    });
    doc.setTextColor(...PDF_COLOR.textPrimary);
  }
}


// ── Footer ────────────────────────────────────────────────────────────────────

/**
 * Adds the footer to the current page.
 * Two items only: brand text on the left, page number on the right.
 * Copyright line removed — it was clustering with the brand text at 7pt.
 */
export function addFooter(doc, pageNum, totalPages) {
  const y = PAGE_HEIGHT - MARGIN.bottom + 6;

  doc.setDrawColor(...PDF_COLOR.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y - 4, PAGE_WIDTH - MARGIN.right, y - 4);

  doc.setFont(PDF_FONT.regular.family, PDF_FONT.regular.style);
  doc.setFontSize(PDF_SIZE.micro);
  doc.setTextColor(...PDF_COLOR.textMuted);

  doc.text(
    "Generated by NG CGPA  |  ngcgpa.ng  |  Built by Nonso [ELUSK]",
    MARGIN.left,
    y,
    { baseline: "top" }
  );

  doc.text(
    `Page ${pageNum} of ${totalPages}`,
    PAGE_WIDTH - MARGIN.right,
    y,
    { align: "right", baseline: "top" }
  );
}


// ── Section Heading ───────────────────────────────────────────────────────────

export function addSectionHeading(doc, title, y) {
  doc.setFillColor(...PDF_COLOR.surface2);
  doc.rect(MARGIN.left, y, CONTENT_WIDTH, 8, "F");

  doc.setFont(PDF_FONT.bold.family, PDF_FONT.bold.style);
  doc.setFontSize(PDF_SIZE.h3);
  doc.setTextColor(...PDF_COLOR.primary);
  doc.text(title.toUpperCase(), MARGIN.left + 3, y + 4.5, {
    baseline: "middle",
  });

  return y + 10;
}


// ── Horizontal Rule ───────────────────────────────────────────────────────────
export function addRule(doc, y, color = PDF_COLOR.border) {
  doc.setDrawColor(...color);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y, PAGE_WIDTH - MARGIN.right, y);
  return y + 4;
}


// ── Key-Value Row ─────────────────────────────────────────────────────────────

export function addKV(doc, label, value, y, labelWidth = 48) {
  doc.setFont(PDF_FONT.bold.family, PDF_FONT.bold.style);
  doc.setFontSize(PDF_SIZE.body);
  doc.setTextColor(...PDF_COLOR.textSecondary);
  doc.text(label, MARGIN.left, y, { baseline: "top" });

  doc.setFont(PDF_FONT.regular.family, PDF_FONT.regular.style);
  doc.setTextColor(...PDF_COLOR.textPrimary);
  doc.text(String(value || "Not provided"), MARGIN.left + labelWidth, y, {
    baseline: "top",
  });

  return y + 6;
}


// ── GPA Bar (for trend section) ───────────────────────────────────────────────

export function addGPABar(doc, label, gpa, scaleMax, y, maxBarWidth = 80) {
  const BAR_HEIGHT = 4;
  const LABEL_W    = 52;
  const barAreaX   = MARGIN.left + LABEL_W;

  const ratio    = Math.min(Math.max(gpa / scaleMax, 0), 1);
  const barWidth = ratio * maxBarWidth;
  const color    = gpa >= scaleMax * 0.90 ? PDF_COLOR.classFirst
                 : gpa >= scaleMax * 0.70 ? PDF_COLOR.classUpper
                 : gpa >= scaleMax * 0.48 ? PDF_COLOR.classLower
                 : PDF_COLOR.danger;

  doc.setFont(PDF_FONT.regular.family, PDF_FONT.regular.style);
  doc.setFontSize(PDF_SIZE.small);
  doc.setTextColor(...PDF_COLOR.textSecondary);
  doc.text(truncateLabel(label, 28), MARGIN.left, y + BAR_HEIGHT / 2, {
    baseline: "middle",
  });

  doc.setFillColor(...PDF_COLOR.surface2);
  doc.roundedRect(barAreaX, y, maxBarWidth, BAR_HEIGHT, 1, 1, "F");

  if (barWidth > 0) {
    doc.setFillColor(...color);
    doc.roundedRect(barAreaX, y, barWidth, BAR_HEIGHT, 1, 1, "F");
  }

  doc.setFont(PDF_FONT.bold.family, PDF_FONT.bold.style);
  doc.setFontSize(PDF_SIZE.small);
  doc.setTextColor(...PDF_COLOR.textPrimary);
  doc.text(
    gpa !== null ? gpa.toFixed(2) : "\u2014",
    barAreaX + maxBarWidth + 3,
    y + BAR_HEIGHT / 2,
    { baseline: "middle" }
  );

  return y + BAR_HEIGHT + 3;
}


// ── autoTable Style Presets ───────────────────────────────────────────────────

export const TABLE_STYLE = {
  semesterBreakdown: {
    theme: "plain",
    headStyles: {
      fillColor:   PDF_COLOR.primary,
      textColor:   [255, 255, 255],
      fontSize:    PDF_SIZE.small,
      fontStyle:   "bold",
      cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
    },
    bodyStyles: {
      fontSize:    PDF_SIZE.body,
      textColor:   PDF_COLOR.textPrimary,
      cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
    },
    alternateRowStyles: {
      fillColor: PDF_COLOR.surface,
    },
    tableLineColor: PDF_COLOR.border,
    tableLineWidth: 0.3,
  },

  courseDetail: {
    theme: "plain",
    headStyles: {
      fillColor:   PDF_COLOR.primaryLight,
      textColor:   [255, 255, 255],
      fontSize:    PDF_SIZE.small,
      fontStyle:   "bold",
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
    },
    bodyStyles: {
      fontSize:    PDF_SIZE.body,
      textColor:   PDF_COLOR.textPrimary,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
    },
    alternateRowStyles: {
      fillColor: PDF_COLOR.surface,
    },
    tableLineColor: PDF_COLOR.border,
    tableLineWidth: 0.2,
  },
};


// ── Helpers ───────────────────────────────────────────────────────────────────

function truncateLabel(str, max) {
  if (!str) return "";
  if (str.length <= max) return str;
  return str.slice(0, max - 1) + "\u2026";
}

export function generateRefId() {
  const hex = () => Math.floor(Math.random() * 65536).toString(16).toUpperCase().padStart(4, "0");
  return `${hex()}-${hex()}-${hex()}-${hex()}`;
}

export function formatPDFDate(date) {
  try {
    const d = date.toLocaleDateString("en-NG", {
      weekday: "long",
      day:     "numeric",
      month:   "long",
      year:    "numeric",
    });
    const t = date.toLocaleTimeString("en-NG", {
      hour:   "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false,
    });
    return `${d} at ${t}`;
  } catch {
    return date.toISOString();
  }
}

export function safeStr(val, fallback = "Not provided") {
  if (val === null || val === undefined || String(val).trim() === "") return fallback;
  return String(val).trim();
}

export function fmtGPA(val) {
  if (val === null || val === undefined || isNaN(val)) return "\u2014";
  return Number(val).toFixed(2);
}